# Generated by Django 2.2.16 on 2022-01-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220129_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',), 'verbose_name_plural': 'Посты'},
        ),
    ]
